repos:
  - repo: https://github.com/ambv/black
    rev: 21.12b0  # Update to the newest version
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8  # Corrected the typo in the repository URL
    rev: 4.0.1  # Update to the newest version
    hooks:
      - id: flake8