# Generated by Django 5.0.4 on 2024-05-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="name",
            field=models.CharField(default="samra", max_length=255),
            preserve_default=False,
        ),
    ]
